name: Build the App

on: push

jobs:
  build:
    name: Build this App
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Print current directory
        run: pwd
      - name: List files in Dir
        run: ls
      - name: CHeck dotnet CLI
        run: dotnet build
      - name: List files in Dir after dotnet build
        run: ls TrickingLibrary.Api/ -R
      - name: Ckeck NPM CLI
        run: npm -v